# Generated by Django 4.1.7 on 2023-02-26 04:46

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, max_length=65535, null=True),
        ),
    ]
